linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - gomnd
    - gosec
    - ifshort
    - makezero
    - misspell
    - prealloc
    - unconvert
    - unparam
    - wastedassign
    - whitespaces
  